### ISSUE TITLE
Horizontal scrollbar CSS bug + enhancements

### ISSUE THREAD

**Issue by HotCakeX** [ar363/eleventy-stylus-blog-theme#18] opened 2023-03-14 13:40 UTC
Hi, I gave this template/theme a try because I was searching for a suitable one for my blog, and in my tests I found some problems with it, thought it'd help to report them.

The main texts in the posts have too much padding on the sides, everything is put inside a small column, when I tried to enlarge it, it was okay when the tab was maximized but when minimizing the tab or using other devices with smaller screens, there is a horizontal scrollbar appearing at the bottom and makes things very hard to use.

the texts need to be made responsive so that they respond to the change in width of the screen size.

Another problem I found is that I couldn't properly modify the hero section in the main page, I wanted to add links etc. but all I could add was text in the description field.

**Comment by ar363** [comment] 2023-03-21 11:57
Ok, so the main issues are:

> The main texts in the posts have too much padding on the sides

It would be better if I aligned the text in the posts with the navigation bar, right? 
But expanding the text to align with the navbar makes it too hard to read, so I need to shrink the navbar itself. 

> using other devices with smaller screens, there is a horizontal scrollbar appearing at the bottom

Some CSS bug, will look into it

> the texts need to be made responsive so that they respond to the change in width of the screen size.

Yeah, I could do that. Any suggested values to reduce the font size to on smaller screens?

> I couldn't properly modify the hero section in the main page, I wanted to add links etc. but all I could add was text in the description field.

Its not a WordPress theme, so there are only so many customizations I could add. Would adding a links array to _data/site.js be an improvement?

Also, I am right now busy with my final exams, so I couldn't work on these issues until at least July. If you are interested, you could work on a PR and I will merge it

**Comment by ar363** [comment] 2023-08-29 05:33
Could not reproduce the horizontal scrollbar issue. Maybe an iphone only thing. Closing...

**Closed as not planned by ar363** 2023-08-29 05:33 UTC
